"""
Local deployment helper for AgriPredictX.
Run: python deploy_local.py
"""

import logging
import platform
import sys
from pathlib import Path

try:
    import psycopg2
    from psycopg2 import sql
except ImportError:
    psycopg2 = None
    sql = None


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


DB_HOST = "localhost"
DB_PORT = 5432
DB_USER = "agripredictx"
DB_PASSWORD = "agripredict123"
DB_NAME = "agripredictx"
DEFAULT_POSTGRES_USER = "postgres"

PROJECT_ROOT = Path(__file__).parent


def check_prerequisites():
    """Choose the best available local deployment mode."""
    logger.info("Checking prerequisites...")
    logger.info("Python %s detected", sys.version.split()[0])

    if psycopg2 is None:
        logger.warning("psycopg2 is not installed, so enhanced mode is unavailable.")
        logger.info("Falling back to basic local API mode")
        return "simple"

    logger.info("psycopg2 installed")

    for connect_kwargs in (
        {
            "host": DB_HOST,
            "port": DB_PORT,
            "user": DEFAULT_POSTGRES_USER,
            "password": "password",
        },
        {
            "host": DB_HOST,
            "port": DB_PORT,
            "user": DEFAULT_POSTGRES_USER,
        },
    ):
        try:
            conn = psycopg2.connect(**connect_kwargs)
            conn.close()
            logger.info("PostgreSQL server is running")
            return "enhanced"
        except Exception:
            pass

    logger.warning("PostgreSQL is not running or not accessible.")
    logger.info("Enhanced mode needs PostgreSQL, but basic local API mode does not.")
    logger.info("Falling back to basic local API mode")
    logger.info("To enable enhanced mode later, start PostgreSQL:")
    if platform.system() == "Windows":
        logger.info("  Windows: Open Services and start PostgreSQL")
        logger.info("  Or: net start postgresql-x64-XX")
    elif platform.system() == "Darwin":
        logger.info("  Mac: brew services start postgresql")
    else:
        logger.info("  Linux: sudo systemctl start postgresql")
    return "simple"


def create_database_user():
    """Create the PostgreSQL user and database for enhanced mode."""
    if psycopg2 is None or sql is None:
        logger.error("psycopg2 is required for enhanced database setup.")
        return False

    logger.info("Setting up PostgreSQL database...")

    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            user=DEFAULT_POSTGRES_USER,
            password="password",
        )
    except Exception:
        try:
            conn = psycopg2.connect(
                host=DB_HOST,
                port=DB_PORT,
                user=DEFAULT_POSTGRES_USER,
            )
        except Exception as exc:
            logger.error("Cannot connect to PostgreSQL: %s", exc)
            return False

    conn.autocommit = True
    cursor = conn.cursor()

    try:
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (DB_USER,))
        if not cursor.fetchone():
            logger.info("Creating PostgreSQL user '%s'...", DB_USER)
            cursor.execute(
                sql.SQL("CREATE USER {} WITH PASSWORD %s").format(
                    sql.Identifier(DB_USER)
                ),
                [DB_PASSWORD],
            )

        cursor.execute("SELECT 1 FROM pg_database WHERE datname = %s", (DB_NAME,))
        if not cursor.fetchone():
            logger.info("Creating PostgreSQL database '%s'...", DB_NAME)
            cursor.execute(
                sql.SQL("CREATE DATABASE {} OWNER {}").format(
                    sql.Identifier(DB_NAME),
                    sql.Identifier(DB_USER),
                )
            )

        cursor.execute(
            sql.SQL("GRANT ALL PRIVILEGES ON DATABASE {} TO {}").format(
                sql.Identifier(DB_NAME),
                sql.Identifier(DB_USER),
            )
        )
        logger.info("Database setup complete")
        return True
    except Exception as exc:
        logger.error("Database setup error: %s", exc)
        return False
    finally:
        cursor.close()
        conn.close()


def create_env_file():
    """Create a .env file for enhanced mode if one is missing."""
    logger.info("Configuring environment variables...")
    env_file = PROJECT_ROOT / ".env"
    env_content = f"""# AgriPredictX Environment Configuration
# Generated by deploy_local.py

# Database Configuration
DATABASE_URL=postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}

# OpenWeatherMap API (optional)
OPENWEATHER_API_KEY=your_api_key_here

# Sentinel-2 Credentials (optional)
SENTINEL_USERNAME=your_username
SENTINEL_PASSWORD=your_password

# Flask Configuration
FLASK_DEBUG=False
FLASK_ENV=production

# Model Configuration
MODEL_PATH=crop_model.pkl

# Logging
LOG_LEVEL=INFO
"""

    try:
        if env_file.exists():
            logger.info(".env file already exists at %s", env_file)
        else:
            env_file.write_text(env_content, encoding="utf-8")
            logger.info(".env file created at %s", env_file)
        return True
    except Exception as exc:
        logger.error("Error creating .env file: %s", exc)
        return False


def initialize_database_schema():
    """Create the enhanced-mode tables."""
    logger.info("Initializing database schema...")

    try:
        from ingestion_layer import DatabaseConnector

        db_url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
        DatabaseConnector(db_url).create_tables()
        logger.info("Database schema initialized")
        return True
    except Exception as exc:
        logger.error("Schema initialization error: %s", exc)
        return False


def verify_installation(enhanced_mode=True):
    """Verify the packages needed for the selected mode."""
    logger.info("Verifying installation...")

    checks = {
        "Flask": lambda: __import__("flask"),
        "Flask-CORS": lambda: __import__("flask_cors"),
        "NumPy": lambda: __import__("numpy"),
        "Pandas": lambda: __import__("pandas"),
        "scikit-learn": lambda: __import__("sklearn"),
        "joblib": lambda: __import__("joblib"),
    }
    if enhanced_mode:
        checks["SQLAlchemy"] = lambda: __import__("sqlalchemy")
        checks["SHAP"] = lambda: __import__("shap")

    all_good = True
    for name, check in checks.items():
        try:
            check()
            logger.info("%s available", name)
        except ImportError:
            logger.warning("%s is not installed", name)
            all_good = False
    return all_good


def start_enhanced_api_server():
    """Start the enhanced Flask API that includes database-backed features."""
    logger.info("Starting AgriPredictX enhanced API server...")

    try:
        from dotenv import load_dotenv
        from api_server_enhanced import app, initialize_system_components

        env_file = PROJECT_ROOT / ".env"
        if env_file.exists():
            load_dotenv(env_file)

        logger.info("Initializing system components...")
        if not initialize_system_components():
            logger.error("Failed to initialize enhanced system components")
            return False

        logger.info("Enhanced API ready at http://localhost:5000/")
        app.run(host="0.0.0.0", port=5000, debug=False, use_reloader=False)
        return True
    except Exception as exc:
        logger.error("Failed to start enhanced API server: %s", exc)
        return False


def start_basic_api_server():
    """Start the simpler Flask API that does not require PostgreSQL."""
    logger.info("Starting AgriPredictX basic API server...")

    try:
        from api_server import app, initialize_app

        logger.info("Initializing prediction stack...")
        if not initialize_app():
            logger.error("Failed to initialize basic API server")
            return False

        logger.info("Basic API ready at http://localhost:5000/")
        app.run(host="0.0.0.0", port=5000, debug=False, use_reloader=False)
        return True
    except Exception as exc:
        logger.error("Failed to start basic API server: %s", exc)
        return False


def main():
    """Execute the local deployment flow."""
    logger.info("=" * 60)
    logger.info("AgriPredictX Local Deployment Script")
    logger.info("=" * 60)

    deployment_mode = check_prerequisites()
    if not deployment_mode:
        logger.error("Prerequisites check failed.")
        return False

    if deployment_mode == "enhanced":
        if not create_database_user():
            logger.error("Database user creation failed.")
            return False
        if not create_env_file():
            logger.error(".env file creation failed.")
            return False
        if not initialize_database_schema():
            logger.warning("Database schema initialization failed. Continuing anyway.")

    if not verify_installation(enhanced_mode=(deployment_mode == "enhanced")):
        logger.warning("Some packages are missing. Install the required dependencies first.")

    logger.info("Ready to start API server in %s mode", deployment_mode)
    response = input("\nStart API server now? (yes/no): ").strip().lower()
    if response not in {"", "y", "yes"}:
        if deployment_mode == "enhanced":
            logger.info("Deployment complete. Start later with: python api_server_enhanced.py")
        else:
            logger.info("Deployment complete. Start later with: python api_server.py")
        return True

    if deployment_mode == "enhanced":
        return start_enhanced_api_server()
    return start_basic_api_server()


if __name__ == "__main__":
    try:
        sys.exit(0 if main() else 1)
    except KeyboardInterrupt:
        logger.info("Deployment cancelled by user")
        sys.exit(0)
